### ISSUE TITLE
[Android] Migrate Mock Server cases in the Internal Test Apps to the PBS 

### ISSUE THREAD

**Issue by YuriyVelichkoPI** [prebid/prebid-mobile-autotests#13]
## Motivation 

Remove dependency to the Mock Server and OpenX's PBS.

## Objective

Update configs of the test cases to work with AWS PBS instead of Mock Server and OpenX. 

## Subtasks 

- [x] Migrate Display Banner tests #21 
- [x] Migrate Video Banner tests #22
- [x] Migrate Display Interstitial tests #23 
- [x] Migrate Video Interstitial tests #24 
- [x] Migrate Rewarded Video tests #25 
- [x] Migrate Native tests #26
