### ISSUE TITLE
[iOS] Migrate Mock Server cases in the Internal Test App to the PBS

### ISSUE THREAD

**Issue by YuriyVelichkoPI** [prebid/prebid-mobile-autotests#33]
## Motivation 

Remove dependency to the Mock Server and OpenX's PBS.

## Objective

Update configs of the test cases to work with AWS PBS instead of Mock Server and OpenX. 

## Subtasks 

- [ ] Migrate Display Banner tests #27 
- [ ] Migrate Video Banner tests #28
- [ ] Migrate Display Interstitial tests #29 
- [ ] Migrate Video Interstitial tests #30 
- [ ] Migrate Rewarded Video tests #31 
- [ ] Migrate Native tests #32
